begin;
create table public.profiles(id uuid primary key references auth.users(id), name text not null, active boolean not null default true, permissions text[] not null default '{}', check(permissions <@ array['admin','clinical','reception','finance']::text[]));
create function public.allowed(p text) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from profiles where id=auth.uid() and active and p=any(permissions)) $$;
create function public.staff() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from profiles where id=auth.uid() and active) $$;
create table public.settings(id integer primary key check(id=1), name text not null default 'Centro de terapias', color text not null default '#17695d', logo text, hourly_reference bigint not null default 5700000);
insert into settings(id) values(1);
create table public.therapies(id uuid primary key default gen_random_uuid(), name text not null unique, active boolean not null default true);
create table public.rates(id integer primary key check(id in(1,2)), name text not null, prices jsonb not null default '{}');
insert into rates values(1,'Tarifa 1','{}'),(2,'Tarifa 2','{}');
create table public.sinpe_numbers(id uuid primary key default gen_random_uuid(), label text not null, phone text not null check(phone ~ '^[0-9]{8}$'), active boolean not null default true);
create table public.templates(id uuid primary key default gen_random_uuid(), name text not null, body text not null);
create table public.patients(id uuid primary key default gen_random_uuid(), document_type text not null check(document_type in('Cédula','DIMEX','Pasaporte')), document text not null, name text not null check(length(trim(name))>1), phone text, email text, preferred_minutes integer check(preferred_minutes in(30,60)), preferred_rate integer references rates(id), source text not null default 'Registro manual', original_date date, consent_care_at timestamptz, consent_reminders_at timestamptz, created_at timestamptz not null default now(), created_by uuid not null default auth.uid() references profiles(id), version integer not null default 1, unique(document_type,document));
create function public.normalize_patient() returns trigger language plpgsql as $$ begin new.document:=upper(regexp_replace(new.document,case when new.document_type='Pasaporte' then '\s' else '[\s-]' end,'','g')); if length(new.document)<3 then raise exception 'Identificación incompleta'; end if; return new; end $$;
create trigger normalize before insert or update on patients for each row execute function normalize_patient();
create index patient_name on patients(lower(name));
create index patient_phone on patients(phone);
create table public.backgrounds(patient_id uuid primary key references patients(id), body text not null default '', updated_by uuid not null default auth.uid() references profiles(id), updated_at timestamptz not null default now(), version integer not null default 1);
create table public.visits(id uuid primary key default gen_random_uuid(), patient_id uuid not null references patients(id), attended_at timestamptz not null default now(), therapist_id uuid not null references profiles(id), created_by uuid not null default auth.uid() references profiles(id), created_at timestamptz not null default now(), status text not null default 'pending' check(status in('pending','running','paused','completed','cancelled')), minutes integer not null check(minutes in(30,60)), rate_name text not null check(rate_name in('Tarifa 1','Tarifa 2','Tarifa modificable')), amount bigint not null check(amount>=0 and amount<=100000000000), free boolean not null default false, adjustment_reason text, started_at timestamptz, segment_at timestamptz, elapsed_seconds integer not null default 0 check(elapsed_seconds>=0), expected_end timestamptz, finished_at timestamptz, alarm_ack boolean not null default false, version integer not null default 1, check(amount>0 or free));
create index visit_patient_date on visits(patient_id,attended_at desc);
create table public.visit_therapies(visit_id uuid references visits(id), therapy_id uuid references therapies(id), therapy_name text not null, primary key(visit_id,therapy_id));
create table public.notes(id uuid primary key default gen_random_uuid(), visit_id uuid not null references visits(id), revision integer not null, reason text, motive text not null default '', symptoms text not null default '', body text not null default '', evolution text not null default '', finalized boolean not null default false, author_id uuid not null default auth.uid() references profiles(id), created_at timestamptz not null default now(), unique(visit_id,revision));
create table public.payments(id uuid primary key default gen_random_uuid(), request_id uuid not null unique, visit_id uuid not null references visits(id), amount bigint not null check(amount>0), method text not null check(method in('Efectivo','SINPE')), status text not null check(status in('pending','confirmed')), sinpe_phone text, sinpe_label text, reference text, received_at timestamptz not null default now(), received_by uuid not null default auth.uid() references profiles(id), confirmed_at timestamptz, confirmed_by uuid references profiles(id), original_id uuid references payments(id), reason text, kind text not null default 'payment' check(kind in('payment','refund')), check(method<>'SINPE' or sinpe_phone is not null), check(kind='payment' or (original_id is not null and reason is not null and length(trim(reason))>0)));
create index payment_date on payments(received_at);
create index payment_visit on payments(visit_id);
create table public.timer_events(id uuid primary key default gen_random_uuid(), visit_id uuid not null references visits(id), action text not null, actor_id uuid not null default auth.uid() references profiles(id), created_at timestamptz not null default now());
create table public.appointments(id uuid primary key default gen_random_uuid(), patient_id uuid not null references patients(id), therapist_id uuid not null references profiles(id), starts_at timestamptz not null, minutes integer not null check(minutes in(30,60)), status text not null default 'scheduled' check(status in('scheduled','cancelled','completed')), created_by uuid not null default auth.uid() references profiles(id), version integer not null default 1);
create table public.audit(id bigint generated always as identity primary key, table_name text not null, record_id text not null, action text not null, actor_id uuid default auth.uid() references profiles(id), at timestamptz not null default now());
create function public.audit_change() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into audit(table_name,record_id,action) values(TG_TABLE_NAME,coalesce(to_jsonb(new)->>'id',to_jsonb(new)->>'patient_id',to_jsonb(new)->>'visit_id'),TG_OP); return new; end $$;
create function public.version_change() returns trigger language plpgsql as $$ begin if new.version<>old.version then raise exception 'Versión inválida'; end if; new.version:=old.version+1; return new; end $$;
do $$ declare t text; begin foreach t in array array['patients','backgrounds','visits','appointments'] loop execute format('create trigger version before update on %I for each row execute function version_change()',t); end loop; foreach t in array array['profiles','patients','backgrounds','visits','notes','payments','appointments','rates','settings','therapies','sinpe_numbers','templates','visit_therapies','timer_events'] loop execute format('create trigger audit after insert or update on %I for each row execute function audit_change()',t); end loop; end $$;
-- No payloads clínicos en auditoría; versiones anteriores en notes, con RLS clínico.
do $$ declare t text; begin foreach t in array array['profiles','settings','therapies','rates','sinpe_numbers','templates','patients','backgrounds','visits','visit_therapies','notes','payments','timer_events','appointments','audit'] loop execute format('alter table %I enable row level security',t); end loop; end $$;
create policy profile_read on profiles for select to authenticated using(staff());
create policy profile_admin on profiles for update to authenticated using(allowed('admin')) with check(allowed('admin'));
do $$ declare t text; begin foreach t in array array['settings','therapies','rates','sinpe_numbers'] loop execute format('create policy read on %I for select to authenticated using (staff())',t); execute format('create policy configure on %I for all to authenticated using (allowed(''admin'')) with check (allowed(''admin''))',t); end loop; end $$;
create policy patient_read on patients for select to authenticated using(staff());
create policy patient_add on patients for insert to authenticated with check((allowed('reception') or allowed('clinical')) and created_by=auth.uid());
create policy patient_edit on patients for update to authenticated using(allowed('reception') or allowed('clinical')) with check(allowed('reception') or allowed('clinical'));
create policy background_read on backgrounds for select to authenticated using(allowed('clinical'));
create policy background_add on backgrounds for insert to authenticated with check(allowed('clinical') and updated_by=auth.uid());
create policy background_edit on backgrounds for update to authenticated using(allowed('clinical')) with check(allowed('clinical') and updated_by=auth.uid());
create policy visit_read on visits for select to authenticated using(staff());
create policy technique_read on visit_therapies for select to authenticated using(staff());
create policy notes_read on notes for select to authenticated using(allowed('clinical'));
create policy templates_read on templates for select to authenticated using(allowed('clinical'));
create policy templates_write on templates for all to authenticated using(allowed('clinical')) with check(allowed('clinical'));
create policy payment_read on payments for select to authenticated using(allowed('finance') or allowed('reception'));
create policy timer_read on timer_events for select to authenticated using(staff());
create policy appointment_read on appointments for select to authenticated using(staff());
create policy appointment_add on appointments for insert to authenticated with check((allowed('reception') or allowed('clinical')) and created_by=auth.uid());
create policy appointment_edit on appointments for update to authenticated using(allowed('reception') or allowed('clinical'));
create policy audit_read on audit for select to authenticated using(allowed('admin'));
grant select on all tables in schema public to authenticated;
grant insert,update on patients,backgrounds,appointments to authenticated;
grant insert,update,delete on templates,therapies,sinpe_numbers to authenticated;
grant update on settings,rates,profiles to authenticated;
create function public.create_visit(p_patient uuid,p_therapist uuid,p_minutes integer,p_rate text,p_amount bigint,p_free boolean,p_reason text,p_therapies uuid[],p_at timestamptz default now()) returns uuid language plpgsql security definer set search_path=public as $$ declare v uuid; configured bigint; begin
 if not(allowed('clinical') or allowed('reception')) then raise exception 'Sin permiso'; end if;
 if not exists(select 1 from profiles where id=p_therapist and active and 'clinical'=any(permissions)) then raise exception 'Terapeuta no autorizado'; end if;
 if p_rate in('Tarifa 1','Tarifa 2') then select (prices->>p_minutes::text)::bigint into configured from rates where name=p_rate; if configured is null then raise exception 'Tarifa pendiente de configurar'; end if; if configured<>p_amount then raise exception 'Tarifa cambió; revisá el monto'; end if; end if;
 if cardinality(p_therapies)<1 or p_therapies is null then raise exception 'Seleccioná una terapia'; end if;
 if exists(select 1 from unnest(p_therapies) t where not exists(select 1 from therapies where id=t and active)) then raise exception 'Terapia no disponible'; end if;
 insert into visits(patient_id,therapist_id,minutes,rate_name,amount,free,adjustment_reason,attended_at) values(p_patient,p_therapist,p_minutes,p_rate,p_amount,p_free,p_reason,p_at) returning id into v;
 insert into visit_therapies select v,id,name from therapies where id=any(p_therapies); return v; end $$;
create function public.timer_action(p_visit uuid,p_version integer,p_action text) returns void language plpgsql security definer set search_path=public as $$ declare v visits; secs integer; begin
 if not(allowed('clinical') or allowed('reception')) then raise exception 'Sin permiso'; end if;
 select * into v from visits where id=p_visit for update; if v.version<>p_version then raise exception 'Otra persona modificó la sesión. Actualizá antes de continuar'; end if;
 secs:=v.elapsed_seconds+case when v.status='running' then greatest(0,extract(epoch from now()-v.segment_at)::integer) else 0 end;
 if p_action='start' and v.status='pending' or p_action='resume' and v.status='paused' then update visits set status='running',started_at=coalesce(started_at,now()),segment_at=now(),expected_end=now()+make_interval(secs=>greatest(0,minutes*60-elapsed_seconds)) where id=p_visit;
 elsif p_action='pause' and v.status='running' then update visits set status='paused',elapsed_seconds=secs,segment_at=null,expected_end=null where id=p_visit;
 elsif p_action='finish' and v.status in('pending','running','paused') then update visits set status='completed',elapsed_seconds=secs,finished_at=now(),segment_at=null,expected_end=null where id=p_visit;
 elsif p_action='cancel' and v.status in('pending','running','paused') then update visits set status='cancelled',elapsed_seconds=secs,finished_at=now(),segment_at=null,expected_end=null where id=p_visit;
 elsif p_action='ack' then update visits set alarm_ack=true where id=p_visit;
 else raise exception 'Transición inválida'; end if;
 insert into timer_events(visit_id,action) values(p_visit,p_action); end $$;
create function public.save_note(p_visit uuid,p_revision integer,p_motive text,p_symptoms text,p_body text,p_evolution text,p_finalized boolean,p_reason text) returns void language plpgsql security definer set search_path=public as $$ declare last_note notes; begin
 if not allowed('clinical') then raise exception 'Sin permiso clínico'; end if;
 perform 1 from visits where id=p_visit for update;
 select * into last_note from notes where visit_id=p_visit order by revision desc limit 1;
 if coalesce(last_note.revision,0)<>p_revision then raise exception 'Conflicto: existe una nota más reciente'; end if;
 if last_note.finalized and coalesce(length(trim(p_reason)),0)=0 then raise exception 'Indicá el motivo de corrección'; end if;
 insert into notes(visit_id,revision,motive,symptoms,body,evolution,finalized,reason) values(p_visit,p_revision+1,p_motive,p_symptoms,p_body,p_evolution,p_finalized,p_reason); end $$;
create function public.record_payment(p_request uuid,p_visit uuid,p_amount bigint,p_method text,p_confirmed boolean,p_sinpe uuid,p_reference text,p_original uuid default null,p_reason text default null) returns uuid language plpgsql security definer set search_path=public as $$ declare result uuid; balance bigint; original payments; receiver sinpe_numbers; refunded bigint; begin
 if not(allowed('finance') or allowed('reception')) then raise exception 'Sin permiso de cobro'; end if;
 perform 1 from visits where id=p_visit for update;
 select * into original from payments where request_id=p_request; if original.id is not null then if original.visit_id<>p_visit or original.amount<>p_amount or original.method<>p_method or original.original_id is distinct from p_original then raise exception 'El reintento corresponde a un movimiento diferente. Revisá el pago anterior'; end if; return original.id; end if;
 if p_method='SINPE' and p_original is null then select * into receiver from sinpe_numbers where id=p_sinpe and active; if receiver.id is null then raise exception 'Número SINPE inválido'; end if; end if;
 select amount-coalesce((select sum(case when kind='refund' then -amount else amount end) from payments where visit_id=p_visit and status='confirmed'),0) into balance from visits where id=p_visit;
 if p_original is null then if p_amount>balance then raise exception 'El abono excede el saldo'; end if;
 else select * into original from payments where id=p_original and visit_id=p_visit and kind='payment' and status='confirmed' for update; if original.id is null then raise exception 'Movimiento original inválido'; end if; select coalesce(sum(amount),0) into refunded from payments where original_id=p_original; if p_amount+refunded>original.amount then raise exception 'Devolución excede movimiento original'; end if; if p_method<>original.method then raise exception 'Usá el método original'; end if; receiver.phone:=original.sinpe_phone; receiver.label:=original.sinpe_label; end if;
 insert into payments(request_id,visit_id,amount,method,status,sinpe_phone,sinpe_label,reference,confirmed_at,confirmed_by,original_id,reason,kind) values(p_request,p_visit,p_amount,p_method,case when p_confirmed then 'confirmed' else 'pending' end,receiver.phone,receiver.label,p_reference,case when p_confirmed then now() end,case when p_confirmed then auth.uid() end,p_original,p_reason,case when p_original is null then 'payment' else 'refund' end) returning id into result; return result; end $$;
create function public.confirm_payment(p_id uuid) returns void language plpgsql security definer set search_path=public as $$ declare p payments; balance bigint; begin
 if not(allowed('finance') or allowed('reception')) then raise exception 'Sin permiso'; end if;
 select * into p from payments where id=p_id; if p.id is null then raise exception 'Pago no encontrado'; end if; perform 1 from visits where id=p.visit_id for update;
 select * into p from payments where id=p_id for update; if p.status='confirmed' then return; end if;
 select amount-coalesce((select sum(case when kind='refund' then -amount else amount end) from payments where visit_id=p.visit_id and status='confirmed'),0) into balance from visits where id=p.visit_id;
 if p.kind='payment' and p.amount>balance then raise exception 'El pago excede el saldo actual'; end if;
 update payments set status='confirmed',confirmed_at=now(),confirmed_by=auth.uid() where id=p_id; end $$;
-- Revocar ejecución pública de funciones: solo las APIs concretas y helpers para RLS.
revoke execute on all functions in schema public from public,anon;
grant execute on function allowed(text),staff(),create_visit(uuid,uuid,integer,text,bigint,boolean,text,uuid[],timestamptz),timer_action(uuid,integer,text),save_note(uuid,integer,text,text,text,text,boolean,text),record_payment(uuid,uuid,bigint,text,boolean,uuid,text,uuid,text),confirm_payment(uuid) to authenticated;
commit;
